site_name: Note traitement fiscal obligations
site_author: Quentin Godfroy
plugins: []
theme:
  name: readthedocs
  locale: fr
markdown_extensions:
  - footnotes
nav:
  - synthese_executive.md
  - note_fiscalisation_obligations.md
  - annexe_tableau_amortissement.md
  - moyens_action.md
  - projet_rescrit.md
